// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPo58q-tMdFS20AnAi6_SbUluwL9TDwPM',
    appId: '1:679993146019:web:637486c9ab51bff0771d16',
    messagingSenderId: '679993146019',
    projectId: 'legalassistantapplication',
    authDomain: 'legalassistantapplication.firebaseapp.com',
    storageBucket: 'legalassistantapplication.firebasestorage.app',
    measurementId: 'G-91JK2L79B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8iHYd49g2KBdYI3ubU-N6YlUw6I65dlc',
    appId: '1:679993146019:android:b1bb49cf75be11ed771d16',
    messagingSenderId: '679993146019',
    projectId: 'legalassistantapplication',
    storageBucket: 'legalassistantapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhXlhKz3Qwka-YgoxEd2zKRpVldjxzjg',
    appId: '1:679993146019:ios:52cfae543be189b7771d16',
    messagingSenderId: '679993146019',
    projectId: 'legalassistantapplication',
    storageBucket: 'legalassistantapplication.firebasestorage.app',
    iosBundleId: 'com.example.legalassistantapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRhXlhKz3Qwka-YgoxEd2zKRpVldjxzjg',
    appId: '1:679993146019:ios:52cfae543be189b7771d16',
    messagingSenderId: '679993146019',
    projectId: 'legalassistantapplication',
    storageBucket: 'legalassistantapplication.firebasestorage.app',
    iosBundleId: 'com.example.legalassistantapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPo58q-tMdFS20AnAi6_SbUluwL9TDwPM',
    appId: '1:679993146019:web:7425d2beff2da483771d16',
    messagingSenderId: '679993146019',
    projectId: 'legalassistantapplication',
    authDomain: 'legalassistantapplication.firebaseapp.com',
    storageBucket: 'legalassistantapplication.firebasestorage.app',
    measurementId: 'G-GQBP98Q2ND',
  );
}
